import React, { Component } from "react";
import Head from "next/head";

export default class Header extends Component {
  render() {
    return (
      <Head>
        <title>Todo By Yuvraj</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    );
  }
}
